# Generated by Django 6.0.3 on 2026-05-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('empleado', models.CharField(max_length=150, verbose_name='Empleado')),
                ('no_cui', models.CharField(max_length=20, verbose_name='No. CUI')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('nombre_puesto', models.CharField(max_length=150, verbose_name='Nombre Puesto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_propietario', models.CharField(max_length=150, verbose_name='Nombre Propietario')),
                ('regimen_tributario', models.CharField(max_length=100, verbose_name='Régimen Tributario')),
                ('tipo_factura', models.CharField(max_length=100, verbose_name='Tipo Factura')),
                ('dias_credito', models.IntegerField(default=0, verbose_name='Días Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
