# Generated by Django 6.0.3 on 2026-05-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empleado_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=50, unique=True, verbose_name='Código artículo')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre_bodega', models.CharField(max_length=200, verbose_name='Nombre Bodega')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad Medida')),
                ('capacidad', models.CharField(max_length=50, verbose_name='Capacidad')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, unique=True, verbose_name='Código Máquina')),
                ('combustible', models.CharField(max_length=10, verbose_name='Combustible S/N')),
                ('id_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Proveedor')),
                ('tipo_maquina', models.CharField(max_length=150, verbose_name='Tipo Máquina')),
                ('marca_maquina', models.CharField(max_length=150, verbose_name='Marca Máquina')),
                ('serie_maquina', models.CharField(max_length=150, verbose_name='Serie Máquina')),
                ('placa_matricula', models.CharField(max_length=50, verbose_name='Placa o Matrícula')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinaria',
                'ordering': ['-created_at'],
            },
        ),
    ]
