# Generated by Django 6.0.3 on 2026-05-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auxiliar_cuenta_labor_marca_municipio_tipomaquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_boleta', models.CharField(max_length=100, verbose_name='No. Boleta')),
                ('fecha_labor', models.DateField(verbose_name='Fecha Labor')),
                ('tipo_servicio', models.CharField(max_length=100, verbose_name='Tipo Servicio')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('codigo_maquina', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Máquina')),
                ('placa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placa')),
                ('operador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Operador')),
                ('finca', models.CharField(max_length=200, verbose_name='Finca')),
                ('lote', models.CharField(max_length=200, verbose_name='Caña / Lote')),
                ('area_lote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Lote (Ha)')),
                ('actividad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actividad')),
                ('labor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Labor')),
                ('corte_semilla', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lote Corte Semilla')),
                ('unidades', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unidades')),
                ('horometro_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Horómetro Inicial')),
                ('horometro_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Horómetro Final')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Unitario')),
                ('num_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Factura')),
                ('cuenta_contable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cuenta Contable')),
                ('variedad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Variedad')),
                ('total_paquetes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Paq/Cajas')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Peso Kg')),
                ('caporal_01', models.CharField(blank=True, max_length=150, null=True, verbose_name='Caporal 01')),
                ('caporal_02', models.CharField(blank=True, max_length=150, null=True, verbose_name='Caporal 02')),
                ('mayordomo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mayordomo')),
                ('administrador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Administrador')),
                ('lugar_origen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Origen')),
                ('lugar_destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Destino')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Operativo',
                'verbose_name_plural': 'Registros Operativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
