# Generated by Django 6.0.3 on 2026-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registrooperativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido'),
        ),
    ]
