# Generated by Django 6.0.3 on 2026-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_make_second_surname_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre Puesto')),
            ],
            options={
                'verbose_name': 'Nombre de Puesto',
                'verbose_name_plural': 'Nombres de Puesto',
                'ordering': ['nombre'],
            },
        ),
    ]
