# Generated by Django 6.0.3 on 2026-08-27 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_nombrepuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='no_cui',
            field=models.CharField(max_length=13, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.RegexValidator('^\\d{1,13}$', 'El No. CUI debe contener únicamente dígitos y no superar 13 caracteres.')], verbose_name='No. CUI'),
        ),
    ]
