# Generated by Django 6.0.3 on 2026-09-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_empleado_no_cui'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=150, verbose_name='Tipo de Servicio')),
                ('fecha', models.DateField(verbose_name='Fecha Programada')),
                ('finca', models.CharField(max_length=200, verbose_name='Finca')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Área (Ha)')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable de la Operación')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Normal', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('En Proceso', 'En Proceso'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=30, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Descripción / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Programación de Operación',
                'verbose_name_plural': 'Programaciones de Operaciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
