# Generated by Django 6.0.3 on 2026-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_programacionoperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('puesto', models.CharField(max_length=150, verbose_name='Puesto')),
                ('area', models.CharField(max_length=150, verbose_name='Área')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma Autorizada',
                'verbose_name_plural': 'Firmas Autorizadas',
                'ordering': ['area', 'nombre'],
            },
        ),
    ]
