# Generated by Django 6.0.3 on 2026-09-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlServicioHorometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, verbose_name='Código Máquina')),
                ('tipo_servicio', models.CharField(max_length=100, verbose_name='Tipo de Servicio Preventivo')),
                ('intervalo_horas', models.IntegerField(default=250, verbose_name='Intervalo (Horas)')),
                ('ultimo_horometro', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Último Horómetro de Servicio')),
                ('proximo_horometro', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Próximo Horómetro Sugerido')),
                ('horometro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Horómetro Actual Registrado')),
                ('estado_alerta', models.CharField(choices=[('Al Día', 'Al Día'), ('Próximo a Vencer', 'Próximo a Vencer'), ('Vencido', 'Vencido')], default='Al Día', max_length=30, verbose_name='Estado de Alerta')),
                ('fecha_ultimo_servicio', models.DateField(blank=True, null=True, verbose_name='Fecha Último Servicio')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control de Servicio por Horómetro',
                'verbose_name_plural': 'Controles de Servicio por Horómetro',
                'ordering': ['codigo_maquina', 'proximo_horometro'],
            },
        ),
        migrations.CreateModel(
            name='DespachoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_vale', models.CharField(max_length=50, unique=True, verbose_name='No. Vale / Ticket')),
                ('fecha', models.DateField(verbose_name='Fecha de Despacho')),
                ('codigo_maquina', models.CharField(max_length=50, verbose_name='Código Máquina')),
                ('tipo_combustible', models.CharField(default='Diésel', max_length=50, verbose_name='Tipo de Combustible')),
                ('galones', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Galones Suministrados')),
                ('horometro_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Horómetro de Carga')),
                ('operador', models.CharField(max_length=150, verbose_name='Operador / Conductor')),
                ('estacion_tanque', models.CharField(max_length=150, verbose_name='Estación / Tanque Suministrador')),
                ('finca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Finca / Ubicación')),
                ('despachado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Despachador Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despacho de Combustible',
                'verbose_name_plural': 'Despachos de Combustibles',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, unique=True, verbose_name='Código Máquina')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Campo', 'En Campo'), ('En Taller', 'En Taller'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Disponible', max_length=30, verbose_name='Estado Operativo')),
                ('finca_actual', models.CharField(blank=True, max_length=150, null=True, verbose_name='Finca / Ubicación Actual')),
                ('operador_asignado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Operador Asignado')),
                ('horometro_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Horómetro Acumulado')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Última Actualización')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Maquinaria',
                'verbose_name_plural': 'Disponibilidad de Maquinarias',
                'ordering': ['codigo_maquina'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=50, unique=True, verbose_name='Código Orden')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('codigo_maquina', models.CharField(max_length=50, verbose_name='Código Máquina')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo'), ('Rutinario', 'Rutinario'), ('Emergencia', 'Emergencia')], default='Preventivo', max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=30, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Taller', 'En Taller'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=30, verbose_name='Estado')),
                ('mecanico', models.CharField(max_length=150, verbose_name='Mecánico / Taller Responsable')),
                ('horometro', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Horómetro de Ingreso')),
                ('falla_reportada', models.TextField(verbose_name='Falla / Motivo de Ingreso')),
                ('trabajos_realizados', models.TextField(blank=True, null=True, verbose_name='Trabajos Realizados')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo (Q)')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Mantenimiento',
                'verbose_name_plural': 'Órdenes de Mantenimiento',
                'ordering': ['-fecha_ingreso', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TanqueCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Tanque')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Tanque')),
                ('tipo_combustible', models.CharField(default='Diésel', max_length=50, verbose_name='Tipo Combustible')),
                ('capacidad_galones', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capacidad Total (Galones)')),
                ('nivel_actual_galones', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nivel Actual (Galones)')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicación / Finca')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('En Reserva', 'En Reserva')], default='Operativo', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tanque de Combustible',
                'verbose_name_plural': 'Tanques de Combustible',
                'ordering': ['codigo'],
            },
        ),
    ]
