# Generated by Django 6.0.3 on 2026-10-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_controlserviciohorometro_despachocombustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrooperativo',
            name='finca_corte_semilla',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Finca de Corte de Semilla'),
        ),
        migrations.AddField(
            model_name='registrooperativo',
            name='lote_corte_semilla',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lote de Corte de Semilla'),
        ),
    ]
