# Generated by Django 6.0.3 on 2026-10-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_repair_maquinaria_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labor',
            options={'ordering': ['proceso', 'codigo'], 'verbose_name': 'Labor', 'verbose_name_plural': 'Labores'},
        ),
        migrations.AddField(
            model_name='labor',
            name='proceso',
            field=models.CharField(choices=[('siembras', 'Siembras'), ('fertilizacion', 'Fertilización'), ('riego', 'Riego')], default='siembras', max_length=20, verbose_name='Proceso'),
        ),
    ]
