"""
Django settings for miproyecto project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Construye rutas dentro del proyecto así: BASE_DIR / 'subdir'.
# La configuración está ubicada en configuraciones/miproyecto/settings.py,
# por lo que la ruta base debe ser la raíz del proyecto.
BASE_DIR = Path(__file__).resolve().parents[2]

# Cargar variables de entorno desde .env
load_dotenv(BASE_DIR / '.env')

# Añadir las carpetas reorganizadas al path de Python para que Django encuentre
# los módulos de backend, frontend y configuraciones.
ROOT_PROJECT_DIR = BASE_DIR
sys.path.insert(0, str(ROOT_PROJECT_DIR / 'Backend'))
sys.path.insert(0, str(ROOT_PROJECT_DIR / 'Frontend'))
sys.path.insert(0, str(ROOT_PROJECT_DIR / 'configuraciones'))


# Configuración de inicio rápido para desarrollo - no apta para producción
# Ver https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: mantiene la clave secreta usada en producción en privado!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG or 'test' in sys.argv:
        SECRET_KEY = 'dev-only-insecure-secret-key'
    else:
        raise ImproperlyConfigured('La variable de entorno SECRET_KEY es obligatoria en producción.')

# Hosts permitidos para desarrollo y producción.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Hosts adicionales (separados por coma en la variable de entorno)
EXTRA_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '')
if EXTRA_HOSTS:
    for host in EXTRA_HOSTS.split(','):
        host = host.strip()
        if host and host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)


# Definición de aplicaciones

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplicaciones locales
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'accounts.middleware.DeviceDetectionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.JWTMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'miproyecto.middleware.SafeExceptionMiddleware',
]

ROOT_URLCONF = 'miproyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Frontend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Redirigir usuarios después de login/logout
LOGIN_REDIRECT_URL = '/modulos/'  # Después de iniciar sesión correctamente (ir a módulos)
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Después de cerrar sesión

WSGI_APPLICATION = 'miproyecto.wsgi.application'


# Base de datos
# En Render, toda escritura de Django debe ir a PostgreSQL (Supabase). SQLite
# queda únicamente como base local de desarrollo.
IS_RENDER_DEPLOY = os.getenv('RENDER', '').lower() == 'true'

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
DB_HOST = os.getenv('DB_HOST', '').strip()
DB_NAME = os.getenv('DB_NAME', '').strip()
DB_USER = os.getenv('DB_USER', '').strip()
DB_PASSWORD = os.getenv('DB_PASSWORD', '').strip()
DB_PORT = os.getenv('DB_PORT', '').strip()

USE_EXTERNAL_POSTGRES = bool(DATABASE_URL) or bool(DB_HOST) or bool(DB_NAME) or bool(DB_USER) or bool(DB_PASSWORD) or bool(DB_PORT)

if IS_RENDER_DEPLOY and not DATABASE_URL:
    raise ImproperlyConfigured(
        'DATABASE_URL debe apuntar a PostgreSQL/Supabase en el entorno de Render; '
        'se cancela el inicio para evitar guardar registros en SQLite efímero.'
    )

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require='postgres' in DATABASE_URL.lower(),
        )
    }
elif USE_EXTERNAL_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME or 'postgres',
            'USER': DB_USER or 'postgres',
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST or 'localhost',
            'PORT': DB_PORT or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Validación de contraseñas
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.PasswordStandardValidator',
    },
]


# Internacionalización
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Archivos estáticos (CSS, JavaScript, Imágenes)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'Frontend' / 'static',
]

# Directorio donde collectstatic recopila archivos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compresión y cache de archivos estáticos (solo en producción)
if not DEBUG:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

# Tipo de campo de clave primaria predeterminado
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Límites de intentos de login para evitar fuerza bruta.
LOGIN_RATE_LIMIT_ATTEMPTS = int(os.getenv('LOGIN_RATE_LIMIT_ATTEMPTS', '3'))
LOGIN_RATE_LIMIT_LOCKOUT_SECONDS = int(os.getenv('LOGIN_RATE_LIMIT_LOCKOUT_SECONDS', '300'))

# Configuración de seguridad básica para sesiones y cookies.
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '3600'))
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.getenv('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True').lower() in ('true', '1', 'yes')
SESSION_COOKIE_HTTPONLY = True
# El token CSRF se lee desde JavaScript para peticiones fetch JSON.
CSRF_COOKIE_HTTPONLY = False
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

USE_HTTPS = os.getenv('USE_HTTPS', 'False').lower() in ('true', '1', 'yes') or os.getenv('RENDER', '').lower() == 'true'

# CSRF y seguridad para Render / proxy reverso.
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

for host in ALLOWED_HOSTS:
    if not host:
        continue
    if host.startswith('http://') or host.startswith('https://'):
        CSRF_TRUSTED_ORIGINS.append(host)
    else:
        CSRF_TRUSTED_ORIGINS.append(f'https://{host}')

if os.getenv('RENDER', '').lower() == 'true' or USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('true', '1', 'yes')
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() in ('true', '1', 'yes')
else:
    SECURE_HSTS_SECONDS = 0
