from Backend import views as backend_views

home = backend_views.home
modulos = backend_views.modulos
configuracion_catalogos = backend_views.configuracion_catalogos
datos_registrados = backend_views.datos_registrados
registros_operativos = backend_views.registros_operativos
registros_operativos_data = backend_views.registros_operativos_data
validar_registro_operativo = backend_views.validar_registro_operativo
editar_registro_operativo = backend_views.editar_registro_operativo
borrar_registro_operativo = backend_views.borrar_registro_operativo
usuarios = backend_views.usuarios
crear_usuario = backend_views.crear_usuario
usuarios_creados = backend_views.usuarios_creados
firmas_autorizadas = backend_views.firmas_autorizadas
operacion = backend_views.operacion
cambiar_estado_operacion = backend_views.cambiar_estado_operacion
eliminar_operacion_programada = backend_views.eliminar_operacion_programada
reportes = backend_views.reportes
indicadores = backend_views.indicadores

# Combustibles
despacho_combustible = backend_views.despacho_combustible
gestionar_despacho_combustible = backend_views.gestionar_despacho_combustible
consumo_combustible = backend_views.consumo_combustible
tanques_combustible = backend_views.tanques_combustible

# Maquinaria y Mantenimiento
ordenes_mantenimiento = backend_views.ordenes_mantenimiento
cambiar_estado_orden_mantenimiento = backend_views.cambiar_estado_orden_mantenimiento
control_horometros = backend_views.control_horometros
estado_maquinaria = backend_views.estado_maquinaria
